# for development only

services:
  www:
    build:
      dockerfile: Dockerfile
      context: ./apps/frontend
    container_name: tracku_www
    restart: always
    # environment:
      # no effect since Dockerfile is from the prebuilt app
      # REACT_APP_IO_SOCKET: ${REACT_APP_IO_SOCKET}
      # REACT_APP_IO_PATH: ${REACT_APP_IO_PATH}
    expose:
      - 80
      - 443
    ports:
      - 8080:80
    networks:
     - default
    #  - tracku
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./apps/backend
    container_name: tracku_api
    restart: on-failure:5
    env_file:
      - ./apps/backend/.env
    environment:
      TRACKU_DB_URI: ${TRACKU_DB_URI}
    expose:
      - 5000
    ports:
     - 5000:5000
    # links:
    #   - db
    networks:
     - default
    #  - tracku
    depends_on:
      - db

  db:
    image: mongo:5.0
    container_name: tracku_db
    volumes:
      - db_data:/data/db
      - ./home:/home
      - ./docker/mongodb_overland/_init:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./docker/mongodb_overland/.env
    # networks:
    #  - default
    #  - tracku
    ports:
      - ${MONGO_HOST_PORT}:27017

volumes:
  db_data:

networks:
  default:
  # tracku:
  #   external: true