version: '3.1'

services:
  www:
    build:
      dockerfile: Dockerfile
      context: ./apps/frontend
    container_name: tracku_www
    restart: always
    environment:
      # no effect since Dockerfile is currently from the prebuilt app
      # REACT_APP_IO_SOCKET: ${REACT_APP_IO_SOCKET}
      # REACT_APP_IO_PATH: ${REACT_APP_IO_PATH}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ${VIRTUAL_PATH_WWW}
    expose:
      - 80
      - 443
    networks:
     - default
     - nginx-proxy
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./apps/backend
    container_name: tracku_api
    restart: on-failure:5
    env_file:
      - ./apps/backend/.env
    environment:
      TRACKU_DB_URI: ${TRACKU_DB_URI}
      TRACKU_IO_PATH: ${TRACKU_IO_PATH}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ${VIRTUAL_PATH_API}
    expose:
      - 5000
    networks:
     - default
     - nginx-proxy
    depends_on:
      - db

  db:
    image: mongo:5.0
    container_name: tracku_db
    volumes:
      - db_data:/data/db
      - ./home:/home
      - ./docker/mongodb_overland/_init:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./docker/mongodb_overland/.env

volumes:
  db_data:

networks:
  default:
  nginx-proxy:
    external: true